version: "3.8"

volumes:
  composer: {}
  db-data:

networks:
  main:

services:
  composer:
    container_name: ${PROJECT_NAME}_composer
    build:
      context: .
      dockerfile: .docker/php/composer/Dockerfile
      args:
        tag: latest
    image: composer
    volumes:
      - composer:/.composer/cache:rw,cached

  app-fpm:
    build:
      context: .
      dockerfile: .docker/php/fpm/Dockerfile
    container_name: ${PROJECT_NAME}_fpm
    image: php:latest
    # command:
    #   ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
    # depends_on:
    #   - rabbitmq
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?serverVersion=5.7
      # - PHP_EXTENSION_AMQP=1
      # - APP_DEBUG=1
    #   - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
    # ports:
    #   - 9000:9000
    networks:
      - main
    volumes:
      - composer:/.composer/cache:rw,cached
      - ./app:/usr/src/app:rw
      - ./var/app:/usr/src/app/var:rw
    # - ./log/web:/var/log/nginx
    # - ./var/app/supervisor:/var/log/supervisor:rw

  server:
    container_name: ${PROJECT_NAME}_server
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    depends_on:
      - app-fpm
    ports:
      - 80:80
      - 443:443
    networks:
      - main
    volumes:
      - ${APP_PATH_HOST}:/usr/src/app/public
      - ./var/server/log:/var/log/nginx
      - ./var/server/cache:/tmp/nginx_cache
      - ./.docker/server/certs:/etc/nginx/ssl:ro,cached
      - ./.docker/server/conf.d:/etc/nginx/conf.d:ro
      - ./.docker/server/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./app:/usr/src/app:ro
